### ISSUE TITLE
HA only finds one instead of multiple P100 plugs

### ISSUE THREAD

**Issue by H4R81** [fishbigger/HomeAssistant-Tapo-P100-Control#14]
Hi there, I'm pretty new to HA, but I manged that one TAPO P100 plug is shown within the enteties. So, in fact I have 5 plugs, which should be shown within the enteties. How should the config entries look alike.

I tried the following versions, but none of them worked out.

Version 01:

 #P100 or P105 Plug
 switch:
     platform: tapo_p100_control
     ip_address: 192.168.xxx.xxx
     email: ***@***.**
     password: **
 
 #P100 or P105 Plug
 switch:
     platform: tapo_p100_control
     ip_address: 192.168.xxx.xxx
     email: ***@***.**
     password: **

Version 02:
 #P100 or P105 Plug
 switch:
     platform: tapo_p100_control
     ip_address: 192.168.xxx.xxx
     email: ***@***.**
     password: **

     platform: tapo_p100_control
     ip_address: 192.168.xxx.xxx
     email: ***@***.**
     password: **

**Comment by richard-scott** [comment]
As long as your indentation is correct, that looks pretty good Yaml.
Are all the 5 devices linked to your Tapo App on your phone?
Once you have named them all in the App, they use those names on HA when it starts up.
If the devices are offline when HA starts they won't show up.

**Comment by H4R81** [comment]
Thanks for your response, but what do you mean with indentation. All of the devices are linked to my Tapo App.

**Comment by richard-scott** [comment]
The indentation is the yaml formatting. It wasn't clear from your original post that you'd created the content like this:

```
#P100 or P105 Plug
switch:
  platform: tapo_p100_control
  ip_address: 192.168.xxx.xxx
  email: @.**
  password: **
```

Also, add some logging to your configuration.yaml to see what errors it produces:

```
logger:
  logs:
    custom_components.tapo_p100_control: DEBUG
```

After restarting Home Assistant there should be sometihng in there regarding the p100 module.

**Comment by H4R81** [comment]
Ok, the logs says that I have duplicate keys for "switch".
2021-03-22 11:42:00 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "switch". Check lines 14 and 21

I'm using the following code:

#P100 or P105 Plug
switch:
platform: tapo_p100_control
ip_address: 192.168.xxx.xxx
email: @.**
password: **

#P100 or P105 Plug
switch:
platform: tapo_p100_control
ip_address: 192.168.xxx.xxx
email: @.**
password: **

After the restart I only find the last device from the config in HA as entity.

**Comment by richard-scott** [comment]
Merge the code:
```
switch:
  #P100 or P105 Plug
  - platform: tapo_p100_control
    ip_address: 192.168.xxx.xxx
    email: @.**
    password: **

  #P100 or P105 Plug
  - platform: tapo_p100_control
    ip_address: 192.168.xxx.xxx
    email: @.**
    password: **
```
